doc(UIKIT-924): Добавлено описание тегов коммита
kaluga-astral/code-style pull request #39
Opened 2023-09-11 12:54 UTC by JetBlackCodes

2023-09-11 12:56 UTC, AndTem requested changes

2023-09-11 12:56 UTC, AndTem commented on packages/commitlint-config/README.md
> +- feat - добавлена новая фича. Для этого enum будет произведен релиз minor версии пакетов
Здесь про релизы инфы либо не должно быть, либо что-то вроде: Можно связать с релизом minor версии npm пакета

2023-11-03 05:31 UTC, AndTem approved these changes

2023-12-13 07:01 UTC, StanislavDa approved these changes

2023-12-13 07:27 UTC, merged