feat(UIKIT-988, eslint-config-react-ts): Добавлено правило consistent-type-imports
kaluga-astral/code-style pull request #44
Opened 2023-11-02 18:02 UTC by Cabagemage

2023-11-02 18:04 UTC, Ofigelov approved these changes

2023-11-03 05:31 UTC, AndTem requested changes

2023-11-03 05:31 UTC, AndTem commented on packages/eslint-config-react-ts/index.js
> +    '@typescript-eslint/consistent-type-imports': 'warn',
Почему не error?

2023-11-03 05:31 UTC, AndTem commented on packages/eslint-config-react-ts/index.js
> +    '@typescript-eslint/consistent-type-imports': 'warn',
На груминге же общались, что мажорную версию выпустим

2023-11-03 05:40 UTC, Cabagemage commented on packages/eslint-config-react-ts/index.js
> +    '@typescript-eslint/consistent-type-imports': 'warn',
Исправил. Показалось, что перестраховаться будет хорошей идеей, но если это мажор, то в этом, не будет смысла. В любом случае, мой косяк.

2023-11-03 05:45 UTC, AndTem approved these changes

2023-11-03 06:09 UTC, merged